version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mark
      - MYSQL_ROOT_USER=root
      - MYSQL_DATABASE=jwtauth
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  goapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - ${DBUSER}
      - ${DBPASS}
      - ${ADDRESS}
      - ${DBNAME}
      - ${JWT_ACCESS_SECRET}
      - ${JWT_REFRESH_SECRET}
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306